export function originalReply(query: string, lang = 'mn'): string {
  const q=query.toLowerCase().normalize('NFKC');const mn=lang==='mn';
  const has=(words:string[])=>words.some(w=>q.includes(w));
  if(has(['захиал','zahial','zahioal','reserve','booking','book','예약','预订','予約','брони','reserv'])) return mn?'Өрөө захиалахын тулд “Захиалга” хэсэгт ирэх, буцах огноо, өрөөний төрөл, зочдын тоо болон холбоо барих мэдээллээ бөглөөрэй. Хүсэлт bataartravel@gmail.com руу илгээгдэнэ. Бааз хариу өгсний дараа захиалга баталгаажна.':'Open the reservation tab and enter your dates, room, guests and contact details. Requests go to bataartravel@gmail.com. The camp must confirm availability before your booking is confirmed.';
  if(has(['имэйл','мэйл','mail','утас','utas','holboo','холбоо','contact','phone','연락','电话','連絡'])) return mn?'Бидэнтэй bataartravel@gmail.com, +976 7201 0099 эсвэл +976 8822 3584 дугаараар холбогдоорой.':'Contact the camp at bataartravel@gmail.com, +976 7201 0099 or +976 8822 3584.';
  if(has(['үнэ','une','өрөө','uruu','room','rate','price','가격','房','preis','tarif','料金'])) return mn?'Люкс, стандарт болон гэр бүлийн өрөөний сонголттой. Гэр бүлийн өрөө нь том давхар ортой мастер өрөө, хувийн шүршүүр болон ариун цэврийн өрөөтэй. Үнэ, сул өрөөг сонгосон огноо, зочдын тоогоор баазаас баталгаажуулна. “Захиалга” хэсгээс хүсэлтээ илгээгээрэй.':'Choose Deluxe, Standard or Family Suite. The family suite has a double-bed master bedroom and private bathroom. Ask the camp to confirm rates and availability for your dates and guest count.';
  if(has(['зам','чиглэл','хаана','байрш','zam','haana','route','location','transfer','pickup','4x4','달란','路线','アクセス'])) return mn?'Бааз Өмнөговь аймгийн Гурвантэс сум, Тост Тосонбумбын нурууны бүсэд байрладаг. Даланзадгадаас очих зам, 4x4 тосох үйлчилгээг баазтай урьдчилан тохироорой: +976 7201 0099.':'The camp is in Gurvantes, South Gobi, near Tost Tosonbumba. Arrange your route and 4x4 transfer from Dalanzadgad with the camp in advance: +976 7201 0099.';
  if(has(['starlink','wifi','wi-fi','интернэт','нарны','цахилгаан','solar','internet','эрчим','시설'])) return mn?'Бааз Starlink интернэт, нарны цахилгаан болон халуун шүршүүртэй. Таны ирэх хугацаанд хэрэгтэй тусгай үйлчилгээний бэлэн байдлыг баазтай урьдчилан баталгаажуулаарай.':'The camp offers Starlink internet, solar power and hot showers. Confirm any specific requirements with the camp before arrival.';
  if(has(['аялал','ayal','ирвэс','irves','цав','khermen','dino','fossil','tour','expedition','leopard','공룡','恐龙'])) return mn?'Тост Тосонбумба, Хүрэн ханын хэц, Хэрмэн цавын чиглэлийн аяллуудтай. Хүссэн чиглэл, огноо, хүний тоогоо хэлбэл захиалгын хүсэлтдээ оруулахад тусална. Ирвэс харах нь байгалийн нөхцөлөөс хамаардаг.':'Explore Tost Tosonbumba, Khuren Khan or Khermen Tsav. Include your preferred route, dates and party size in the reservation request. Wildlife sightings depend on natural conditions.';
  if(has(['сайн','sain','hello','hi','안녕','你好','こんにちは'])) return mn?'Сайн байна уу! Өрөө, захиалга, зам чиглэл, аялал, үйлчилгээний талаар асуугаарай. Танд ямар мэдээлэл хэрэгтэй вэ?':'Welcome! Ask about rooms, reservations, directions, tours or camp facilities.';
  return mn?'Энэ асуултын баталгаатай мэдээлэл лавлахад алга. Илүү тодруулж бичих эсвэл bataartravel@gmail.com / +976 7201 0099 дугаараар баазтай холбогдоорой.':'I do not have verified information for that question. Please clarify or contact bataartravel@gmail.com / +976 7201 0099.';
}

const localized: Record<string,string[]> = {
 mn:['Батаарын өлгийд тавтай морилно уу! Өрөө, зам, аялал, захиалгын талаар асуугаарай. Үнэ, сул байрыг бааз батална.','Захиалгын маягтад огноо, хүний тоо, холбоо барих мэдээллээ оруулна уу. Бааз сул байр болон эцсийн үнийг баталсны дараа төлбөрийн холбоос өгнө.','Gmail дээр хүсэлт бэлдэх','Имэйл апп дээр хүсэлт бэлдэх','Имэйл автоматаар илгээгдэхгүй. Мэдээллээ бичээд өөрөө илгээнэ үү.'],
 en:['Welcome to Bataar Sanctuary! Ask about rooms, directions, tours or bookings. The camp confirms prices and availability.','Enter dates, guest count and contact details in the reservation form. The camp confirms availability and price before providing a payment link.','Prepare a request in Gmail','Prepare a request in your email app','Email is not sent automatically. Add your details and send it yourself.'],
 ko:['바타르 생추어리에 오신 것을 환영합니다! 객실, 길 안내, 여행과 예약을 문의하세요. 가격과 객실 가능 여부는 캠프에서 확인합니다.','예약 양식에 날짜, 인원과 연락처를 입력하세요. 캠프에서 가능 여부와 가격을 확인한 후 결제 링크를 제공합니다.','Gmail에서 요청 작성','이메일 앱에서 요청 작성','자동으로 전송되지 않습니다. 정보를 입력하고 직접 보내세요.'],
 zh:['欢迎来到巴塔尔营地！您可以询问客房、路线、旅行和预订。价格和空房由营地确认。','请在预订表单填写日期、人数和联系方式。营地确认空房与价格后会提供付款链接。','在 Gmail 中撰写请求','在邮件应用中撰写请求','邮件不会自动发送。请填写信息后自行发送。'],
 ja:['バタール・サンクチュアリへようこそ！客室、道順、ツアー、予約についてご質問ください。料金と空室はキャンプが確認します。','予約フォームに日程、人数、連絡先を入力してください。キャンプが空室と料金を確認した後、支払いリンクを提供します。','Gmailでリクエストを作成','メールアプリでリクエストを作成','メールは自動送信されません。情報を入力してご自身で送信してください。'],
 ru:['Добро пожаловать в Bataar Sanctuary! Спросите о номерах, маршрутах, экскурсиях или бронировании. Цены и наличие подтверждает база.','Укажите даты, количество гостей и контакты в форме. База подтвердит наличие и цену, затем предоставит ссылку для оплаты.','Подготовить заявку в Gmail','Подготовить заявку в почтовом приложении','Письмо не отправляется автоматически. Заполните данные и отправьте его самостоятельно.'],
 de:['Willkommen im Bataar Sanctuary! Fragen Sie nach Zimmern, Anreise, Touren oder Buchungen. Das Camp bestätigt Preise und Verfügbarkeit.','Tragen Sie Datum, Gästezahl und Kontakt in das Formular ein. Das Camp bestätigt Verfügbarkeit und Preis und stellt danach einen Zahlungslink bereit.','Anfrage in Gmail vorbereiten','Anfrage in der E-Mail-App vorbereiten','Die E-Mail wird nicht automatisch gesendet. Ergänzen Sie Ihre Angaben und senden Sie sie selbst.'],
 fr:['Bienvenue à Bataar Sanctuary ! Posez vos questions sur les chambres, les trajets, les excursions ou les réservations. Le camp confirme les prix et disponibilités.','Indiquez les dates, le nombre de personnes et vos coordonnées dans le formulaire. Le camp confirme disponibilité et prix avant de fournir un lien de paiement.','Préparer une demande dans Gmail','Préparer une demande dans votre application mail','Le message ne sera pas envoyé automatiquement. Ajoutez vos informations et envoyez-le vous-même.'],
 it:['Benvenuti a Bataar Sanctuary! Chiedete informazioni su camere, percorsi, escursioni o prenotazioni. Il campo conferma prezzi e disponibilità.','Inserite date, numero di ospiti e contatti nel modulo. Il campo conferma disponibilità e prezzo prima di fornire il link di pagamento.','Preparare una richiesta in Gmail','Preparare una richiesta nell’app email','L’email non viene inviata automaticamente. Inserite i vostri dati e inviatela personalmente.'],
};
const details: Record<string,string[]> = {
 ko:['디럭스, 스탠더드, 패밀리 객실이 있습니다. 날짜별 가격과 가능 여부를 캠프에 확인하세요.','캠프는 남고비 구르반테스의 토스트 토손붐바 인근입니다. 달란자드가드에서 오는 경로와 4x4 픽업을 미리 예약하세요.','Starlink 인터넷, 태양광 전력, 온수 샤워가 있습니다. 필요한 서비스를 방문 전에 확인하세요.','토스트 토손붐바나 헤르멘 차브 여행 경로를 요청에 적어 주세요. 야생동물 관찰은 자연 조건에 따라 달라집니다.','확인된 정보가 없습니다. 자세히 질문하거나 캠프에 문의하세요.'],
 zh:['有豪华、标准和家庭客房。请向营地确认价格与空房。','营地位于南戈壁古尔班特斯，靠近托斯特托松本巴。请提前安排从达兰扎德嘎德出发的路线和四驱接送。','提供 Starlink 网络、太阳能电力和热水淋浴。请提前确认特殊需求。','请注明托斯特托松本巴或赫尔门察夫路线。野生动物能否出现取决于自然条件。','没有该问题的已核实信息。请说明更多细节或联系营地。'],
 ja:['デラックス、スタンダード、ファミリー客室があります。料金と空室をキャンプに確認してください。','キャンプは南ゴビのグルバンテス、トスト・トソンブンバ付近です。ダランザドガドからの道順と四輪駆動送迎を事前に手配してください。','Starlink、太陽光電力、温水シャワーがあります。必要なサービスを到着前に確認してください。','トスト・トソンブンバやヘルメンツァブの希望ルートを記入してください。野生動物との遭遇は自然条件に左右されます。','確認済み情報がありません。詳細をお伝えいただくかキャンプへお問い合わせください。'],
 ru:['Есть номера Deluxe, Standard и Family. Уточните цены и наличие на ваши даты.','База находится в Гурвантесе, Южная Гоби, рядом с Тост-Тосонбумбой. Заранее согласуйте маршрут и трансфер 4x4 из Даланзадгада.','Есть Starlink, солнечная электроэнергия и горячий душ. Уточните особые требования до приезда.','Укажите маршрут в Тост-Тосонбумбу или Хэрмэн-Цав. Наблюдение за животными зависит от природных условий.','Нет проверенной информации. Уточните вопрос или свяжитесь с базой.'],
 de:['Es gibt Deluxe-, Standard- und Familienzimmer. Lassen Sie Preise und Verfügbarkeit bestätigen.','Das Camp liegt in Gurvantes in der Südgobi bei Tost Tosonbumba. Vereinbaren Sie Anreise und 4x4-Transfer aus Dalanzadgad im Voraus.','Starlink, Solarstrom und warme Duschen sind vorhanden. Bestätigen Sie besondere Anforderungen vor der Anreise.','Geben Sie Ihre Route nach Tost Tosonbumba oder Khermen Tsav an. Wildtiersichtungen hängen von natürlichen Bedingungen ab.','Dazu habe ich keine bestätigten Informationen. Bitte präzisieren Sie die Frage oder kontaktieren Sie das Camp.'],
 fr:['Des chambres Deluxe, Standard et familiales sont proposées. Faites confirmer prix et disponibilité.','Le camp se situe à Gurvantes, dans le Gobi du Sud, près de Tost Tosonbumba. Organisez votre transfert 4x4 depuis Dalanzadgad à l’avance.','Le camp dispose de Starlink, d’énergie solaire et de douches chaudes. Confirmez vos besoins avant votre arrivée.','Indiquez votre itinéraire à Tost Tosonbumba ou Khermen Tsav. Les observations d’animaux dépendent des conditions naturelles.','Je ne dispose pas d’informations vérifiées. Précisez votre demande ou contactez le camp.'],
 it:['Sono disponibili camere Deluxe, Standard e Family. Chiedete conferma di prezzi e disponibilità.','Il campo si trova a Gurvantes, nel Gobi meridionale, vicino a Tost Tosonbumba. Concordate in anticipo il percorso e il trasferimento 4x4 da Dalanzadgad.','Sono disponibili Starlink, energia solare e docce calde. Confermate esigenze particolari prima dell’arrivo.','Indicate il percorso desiderato a Tost Tosonbumba o Khermen Tsav. Gli avvistamenti dipendono dalle condizioni naturali.','Non ho informazioni verificate. Precisate la domanda o contattate il campo.'],
};
export function publicConciergeCopy(lang:string) {const c=localized[lang]||localized.en;return {welcome:c[0],bookingDescription:c[1],gmail:c[2],emailApp:c[3],emailNotice:c[4]};}
export function conciergeReply(query:string,lang='mn'):string {
 const q=query.toLowerCase().normalize('NFKC');const has=(words:string[])=>words.some(w=>q.includes(w));
 if(has(['захиал','zahial','reserve','booking','book','예약','预订','予約','брони','reserv','buchen','prenot'])) return publicConciergeCopy(lang).bookingDescription;
 if(has(['сайн','sain','hello','안녕','你好','こんにちは','привет','hallo','bonjour','ciao','salve']))return publicConciergeCopy(lang).welcome;
 if(lang==='mn'||lang==='en')return originalReply(query,lang);
 const d=details[lang]||details.en;
 if(has(['имэйл','mail','утас','contact','phone','연락','电话','連絡','kontakt','контакт','contatt']))return 'bataartravel@gmail.com / +976 7201 0099 / +976 8822 3584';
 if(has(['room','rate','price','가격','객실','房','preis','zimmer','tarif','料金','客室','номер','цен','chambre','camera','prezz']))return d[0];
 if(has(['route','location','transfer','pickup','4x4','달란','길','路线','アクセス','道順','маршрут','anreise','trajet','percor','trasfer']))return d[1];
 if(has(['starlink','wifi','wi-fi','solar','internet','시설','网络','星链','电力','設備','услуг','équipement','serviz']))return d[2];
 if(has(['khermen','dino','fossil','tour','expedition','leopard','공룡','여행','恐龙','旅行','тур','экскурс','ausflug','excursion','escursion']))return d[3];
 return d[4];
}

