export const roomBookingCopy = {
  mn: ['Өрөөний захиалга','Хаах','Байр + өдрийн 3 хоол. Аяллын төлбөр тусдаа.','Өрөөний төрөл','Хүний тоо','Ирэх огноо','Гарах огноо','Энгийн өрөө','Люкс өрөө','Гэр бүлийн өрөө','өрөө','хүн','хоног','Байр + 3 хоол','Ирэх, гарах огноогоо сонгоно уу','Бааз сул байр, өрөөний хуваарилалт, эцсийн MNT үнийг батална. Аяллын үнэ тусдаа.','Захиалгын хүсэлт илгээх','Дараагийн маягтад холбоо барих мэдээллээ бөглөнө. Бааз баталсны дараа QPay төлбөрийн холбоос өгнө.','USD дүн нь ойролцоо тооцоо. Төлбөр MNT.'],
  en: ['Request a room','Close','Accommodation and three meals daily. Tours cost extra.','Room type','Guests','Arrival','Departure','Standard room','Deluxe room','Family room','rooms','guests','nights','Stay and three meals','Select arrival and departure dates','The camp confirms availability, room allocation and the final MNT price. Tours cost extra.','Continue to booking request','Enter your contact details on the next form. After confirmation, the camp provides a QPay payment link.','USD amounts are indicative. Payment is in MNT.'],
  ko: ['객실 예약 문의','닫기','숙박과 하루 세 끼 식사. 투어 비용은 별도입니다.','객실 유형','인원','체크인 날짜','체크아웃 날짜','스탠다드룸','디럭스룸','패밀리룸','객실','명','박','숙박과 세 끼 식사','체크인 및 체크아웃 날짜를 선택하세요','캠프에서 객실 가능 여부, 배정 및 최종 MNT 가격을 확인합니다. 투어 비용은 별도입니다.','예약 요청 계속하기','다음 양식에 연락처를 입력하세요. 캠프 확인 후 QPay 결제 링크를 제공합니다.','USD 금액은 참고용입니다. 결제 통화는 MNT입니다.'],
  zh: ['申请预订客房','关闭','住宿及每日三餐。游览费用另计。','房型','人数','入住日期','离店日期','标准房','豪华房','家庭房','间客房','位客人','晚','住宿及三餐','请选择入住和离店日期','营地将确认空房、客房分配及最终 MNT 价格。游览费用另计。','继续填写预订申请','请在下一页填写联系方式。营地确认后将提供 QPay 付款链接。','美元金额仅供参考。付款币种为 MNT。'],
  ja: ['客室予約のリクエスト','閉じる','宿泊と毎日3食。ツアー料金は別途です。','客室タイプ','人数','到着日','出発日','スタンダードルーム','デラックスルーム','ファミリールーム','室','名','泊','宿泊と3食','到着日と出発日を選択してください','キャンプが空室、客室割り当て、最終MNT料金を確認します。ツアー料金は別途です。','予約リクエストに進む','次のフォームに連絡先を入力してください。確認後、キャンプがQPay決済リンクを提供します。','USD金額は目安です。支払い通貨はMNTです。'],
  ru: ['Заявка на размещение','Закрыть','Проживание и трёхразовое питание. Экскурсии оплачиваются отдельно.','Тип номера','Гости','Дата заезда','Дата выезда','Стандартный номер','Номер делюкс','Семейный номер','номера','гостей','ночей','Проживание и три приёма пищи','Выберите даты заезда и выезда','База подтвердит наличие мест, распределение номеров и итоговую цену в MNT. Экскурсии оплачиваются отдельно.','Перейти к заявке','Укажите контакты в следующей форме. После подтверждения база предоставит ссылку для оплаты через QPay.','Сумма в USD ориентировочная. Оплата в MNT.'],
  de: ['Zimmer anfragen','Schließen','Unterkunft und drei Mahlzeiten täglich. Touren kosten extra.','Zimmertyp','Gäste','Anreise','Abreise','Standardzimmer','Deluxe-Zimmer','Familienzimmer','Zimmer','Gäste','Nächte','Unterkunft und drei Mahlzeiten','Anreise und Abreise wählen','Das Camp bestätigt Verfügbarkeit, Zimmeraufteilung und den endgültigen Preis in MNT. Touren kosten extra.','Weiter zur Buchungsanfrage','Geben Sie im nächsten Formular Ihre Kontaktdaten ein. Nach Bestätigung erhalten Sie einen QPay-Zahlungslink.','USD-Beträge dienen zur Orientierung. Zahlung in MNT.'],
  fr: ['Demander une chambre','Fermer','Hébergement et trois repas par jour. Excursions en supplément.','Type de chambre','Voyageurs','Arrivée','Départ','Chambre standard','Chambre deluxe','Chambre familiale','chambres','voyageurs','nuits','Hébergement et trois repas','Choisissez les dates d’arrivée et de départ','Le camp confirme les disponibilités, la répartition des chambres et le prix final en MNT. Excursions en supplément.','Continuer la demande','Saisissez vos coordonnées dans le formulaire suivant. Après confirmation, le camp fournit un lien de paiement QPay.','Les montants en USD sont indicatifs. Paiement en MNT.'],
  it: ['Richiedi una camera','Chiudi','Soggiorno e tre pasti al giorno. Escursioni a parte.','Tipo di camera','Ospiti','Arrivo','Partenza','Camera standard','Camera deluxe','Camera familiare','camere','ospiti','notti','Soggiorno e tre pasti','Scegli le date di arrivo e partenza','Il campo conferma disponibilità, assegnazione delle camere e prezzo finale in MNT. Escursioni a parte.','Continua la richiesta','Inserisci i recapiti nel modulo successivo. Dopo la conferma, il campo fornisce un link di pagamento QPay.','Gli importi in USD sono indicativi. Pagamento in MNT.'],
} as const;
export type RoomBookingLanguage = keyof typeof roomBookingCopy;
